# Generated by Django 3.0 on 2020-10-27 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cattiposespecificosinversiones',
            name='cat_tipos_inversiones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='declaracion.CatTiposInversiones'),
        ),
    ]
