# Generated by Django 3.0 on 2020-12-04 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0002_cattiposespecificosinversiones_cat_tipos_inversiones'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatAreas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(blank=True, max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='catpuestos',
            name='cat_areas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='declaracion.CatAreas'),
        ),
    ]
