# Generated by Django 3.0 on 2021-03-11 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0004_auto_20210107_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopersonalfija',
            name='cat_puestos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='declaracion.CatPuestos', verbose_name='Puesto'),
        ),
    ]
