# Generated by Django 3.0 on 2021-03-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0005_infopersonalfija_cat_puestos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catpuestos',
            name='codigo',
            field=models.IntegerField(default=0),
        ),
    ]
