# Generated by Django 3.0 on 2021-03-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0006_auto_20210312_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='secciones',
            name='simp',
            field=models.IntegerField(default=0),
        ),
    ]
