# Generated by Django 3.0 on 2021-03-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0007_secciones_simp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopersonalfija',
            name='puesto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
