# Generated by Django 3.0 on 2021-05-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('declaracion', '0008_auto_20210329_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deudasotros',
            name='acreedor_infopersonalvar',
        ),
        migrations.AddField(
            model_name='deudasotros',
            name='acredor_es_fisica',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='deudasotros',
            name='tercero_infopersonalvar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='declaracion.InfoPersonalVar'),
        ),
        migrations.AlterField(
            model_name='infopersonalfija',
            name='apellido1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='infopersonalfija',
            name='apellido2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Apellido Materno'),
        ),
    ]
