# Generated by Django 3.0 on 2020-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='declaracion_faqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField(default=0, verbose_name='Orden (si tiene cero es omitido)')),
                ('pregunta', models.CharField(default='', max_length=3000, verbose_name='Pregunta')),
                ('respuesta', models.CharField(default='', max_length=3000, verbose_name='Respuesta')),
            ],
            options={
                'verbose_name': 'Preguntas Frecuentes sobre declaraciones',
                'verbose_name_plural': 'Preguntas Frecuentes sobre declaraciones',
            },
        ),
        migrations.CreateModel(
            name='sitio_personalizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(default='Sin nombrar', max_length=300, verbose_name='Nombre de la institución')),
                ('siglas_sistema', models.CharField(default='SN', max_length=30, verbose_name='Siglas del sistema')),
                ('direccion_calle', models.CharField(default='Sin nombrar', max_length=300, verbose_name='Calle, número y numero interior de la institución')),
                ('direccion_cp', models.CharField(default='Sin nombrar', max_length=300, verbose_name='código postal de la institución')),
                ('direccion_ciudad', models.CharField(default='Sin nombrar', max_length=300, verbose_name='ciudad de la institución')),
                ('direccion_estado', models.CharField(default='Jalisco', max_length=300, verbose_name='estado de la institución')),
                ('direccion_telefonos', models.CharField(default='sn', max_length=300, verbose_name='telefonos de la institución')),
                ('direccion_correos', models.CharField(default='sn', max_length=300, verbose_name='correos electrónico de la institución')),
                ('google_captcha_sitekey', models.CharField(default='6LdVTt0UAAAAAEkz8C_gBLX8F4O4cJZt762TDgvW', max_length=300, verbose_name='Clave sitio web para el captcha de Google ')),
                ('google_captcha_secretkey', models.CharField(blank=True, max_length=300, null=True, verbose_name='Clave secreta captcha de Google ')),
                ('terminosCondiciones_registro', models.FileField(default='personalizar/terminos_y_Condiciones_registro.pdf', max_length=300, upload_to='personalizar/', verbose_name='PDF con los terminos y condiciones al registrarse')),
                ('imagen_logo', models.ImageField(default='personalizar/default_logo.png', max_length=300, upload_to='personalizar/', verbose_name='imagen logo')),
                ('imagen_sublogo', models.ImageField(default='personalizar/default_logo_simple.png', max_length=300, upload_to='personalizar/', verbose_name='imagen logo simplificado ')),
                ('imagen_inicioFondo', models.ImageField(default='personalizar/default_fondo_index.png', max_length=300, upload_to='personalizar/', verbose_name='imagen fondo del index')),
                ('imagen_inicioPiepagina', models.ImageField(default='personalizar/default_footer_index.png', max_length=300, upload_to='personalizar/', verbose_name='imagen pie de página del index')),
                ('imagen_defaultPerfil', models.ImageField(default='personalizar/default_image_perfil.png', max_length=300, upload_to='personalizar/', verbose_name='imagen default para el perfil de usuario')),
                ('color_base', models.CharField(default='#fff', max_length=20, verbose_name='Color base (default=#fff)')),
                ('color_obscuro', models.CharField(default='#000', max_length=20, verbose_name='Color obscuro (default=#000)')),
                ('color_primario', models.CharField(default='#015F78', max_length=20, verbose_name='Color primario (default=#015F78)')),
                ('color_secundario', models.CharField(default='#A4B54C', max_length=20, verbose_name='Color secundario (default=#A4B54C)')),
                ('color_neutro', models.CharField(default='#F2F2F2', max_length=20, verbose_name='Color neutro (default=#F2F2F2)')),
                ('color_suceso', models.CharField(default='#5dffff', max_length=20, verbose_name='Color suceso (default=#5dffff)')),
                ('color_peligro', models.CharField(default='#38A6F9', max_length=20, verbose_name='Color peligro (default=#38A6F9)')),
                ('color_alerta', models.CharField(default='#dc3545', max_length=20, verbose_name='Color error (default=#dc3545)')),
            ],
            options={
                'verbose_name': 'personalización del sitio',
                'verbose_name_plural': 'personalización del sitio',
            },
        ),
        migrations.CreateModel(
            name='Valores_SMTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailaddress', models.CharField(max_length=300, verbose_name='Correo')),
                ('mailpassword', models.CharField(max_length=200, verbose_name='Contraseña')),
                ('nombre_smtp', models.CharField(max_length=200, verbose_name='SMTP')),
                ('puerto', models.IntegerField(verbose_name='Puerto')),
            ],
        ),
    ]
