# Generated by Django 3.0 on 2021-01-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0003_auto_20201105_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio_personalizacion',
            name='fecha_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sitio_personalizacion',
            name='fecha_incio',
            field=models.DateTimeField(null=True),
        ),
    ]
