# Generated by Django 3.0 on 2021-01-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_auto_20210107_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitio_personalizacion',
            name='fecha_fin',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='sitio_personalizacion',
            name='fecha_incio',
            field=models.DateField(null=True),
        ),
    ]
