# Generated by Django 3.0 on 2021-01-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0005_auto_20210107_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitio_personalizacion',
            name='declaracion_modificacion_crear',
            field=models.BooleanField(default=True, verbose_name='Crear declaración de modificación de manera abierta'),
        ),
    ]
